MERGE (Confirmed_diagnosis_and_clinical_stage:Decision {id:'Confirmed-diagnosis-and-clinical-stage', name:'Confirmed diagnosis and clinical stage'})
MERGE (cT_stage:ClinicalParameter {name:'cT-stage'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_INPUT]->(cT_stage)
MERGE (cN_stage:ClinicalParameter {name:'cN-stage'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_INPUT]->(cN_stage)
MERGE (M_stage:ClinicalParameter {name:'M-stage'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_INPUT]->(M_stage)
MERGE (histological_type:ClinicalParameter {name:'histological-type'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_INPUT]->(histological_type)
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0:DecisionRule {id:'rule_Confirmed_diagnosis_and_clinical_stage_0'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_RULE]->(rule_Confirmed_diagnosis_and_clinical_stage_0)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cT_stage:Condition {param:'cT_stage', value:'_cTis_DCIS__'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cT_stage)-[:CONDITION_ON]->(cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cN_stage:Condition {param:'cN_stage', value:'_cN0_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_cN_stage)-[:CONDITION_ON]->(cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_M_stage:Condition {param:'M_stage', value:'_M0_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_0_M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_M_stage)-[:CONDITION_ON]->(M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_histological_type:Condition {param:'histological_type', value:'_DCIS_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_0_histological_type)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_0_histological_type)-[:CONDITION_ON]->(histological_type)
MERGE (outcome_rule_Confirmed_diagnosis_and_clinical_stage_0__DCIS_1_:ActionRecommendation {name:'"DCIS-1"'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_0)-[:HAS_OUTCOME]->(outcome_rule_Confirmed_diagnosis_and_clinical_stage_0__DCIS_1_)
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1:DecisionRule {id:'rule_Confirmed_diagnosis_and_clinical_stage_1'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_RULE]->(rule_Confirmed_diagnosis_and_clinical_stage_1)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cT_stage:Condition {param:'cT_stage', value:'_cT1___cT1mi___cT1a___cT1b___cT1c___cT2___cT3_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cT_stage)-[:CONDITION_ON]->(cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cN_stage:Condition {param:'cN_stage', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_cN_stage)-[:CONDITION_ON]->(cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_M_stage:Condition {param:'M_stage', value:'_M0_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_1_M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_M_stage)-[:CONDITION_ON]->(M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_histological_type:Condition {param:'histological_type', value:'not__DCIS___Paget_s_disease__'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_1_histological_type)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_1_histological_type)-[:CONDITION_ON]->(histological_type)
MERGE (outcome_rule_Confirmed_diagnosis_and_clinical_stage_1__BINV_1_:ActionRecommendation {name:'"BINV-1"'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_1)-[:HAS_OUTCOME]->(outcome_rule_Confirmed_diagnosis_and_clinical_stage_1__BINV_1_)
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2:DecisionRule {id:'rule_Confirmed_diagnosis_and_clinical_stage_2'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_RULE]->(rule_Confirmed_diagnosis_and_clinical_stage_2)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cT_stage:Condition {param:'cT_stage', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cT_stage)-[:CONDITION_ON]->(cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cN_stage:Condition {param:'cN_stage', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_cN_stage)-[:CONDITION_ON]->(cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_M_stage:Condition {param:'M_stage', value:'_M1_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_2_M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_M_stage)-[:CONDITION_ON]->(M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_histological_type:Condition {param:'histological_type', value:'not__DCIS___Paget_s_disease__'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_2_histological_type)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_2_histological_type)-[:CONDITION_ON]->(histological_type)
MERGE (outcome_rule_Confirmed_diagnosis_and_clinical_stage_2__BINV_18_:ActionRecommendation {name:'"BINV-18"'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_2)-[:HAS_OUTCOME]->(outcome_rule_Confirmed_diagnosis_and_clinical_stage_2__BINV_18_)
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3:DecisionRule {id:'rule_Confirmed_diagnosis_and_clinical_stage_3'})
MERGE (Confirmed_diagnosis_and_clinical_stage)-[:HAS_RULE]->(rule_Confirmed_diagnosis_and_clinical_stage_3)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cT_stage:Condition {param:'cT_stage', value:'_cT4d_'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cT_stage)-[:CONDITION_ON]->(cT_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cN_stage:Condition {param:'cN_stage', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_cN_stage)-[:CONDITION_ON]->(cN_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_M_stage:Condition {param:'M_stage', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_3_M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_M_stage)-[:CONDITION_ON]->(M_stage)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_histological_type:Condition {param:'histological_type', value:'Unknown'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3)-[:HAS_CONDITION]->(cond_rule_Confirmed_diagnosis_and_clinical_stage_3_histological_type)
MERGE (cond_rule_Confirmed_diagnosis_and_clinical_stage_3_histological_type)-[:CONDITION_ON]->(histological_type)
MERGE (outcome_rule_Confirmed_diagnosis_and_clinical_stage_3__IBC_1_:ActionRecommendation {name:'"IBC-1"'})
MERGE (rule_Confirmed_diagnosis_and_clinical_stage_3)-[:HAS_OUTCOME]->(outcome_rule_Confirmed_diagnosis_and_clinical_stage_3__IBC_1_)
MERGE (Evaluation_for_metastatic_therapy:Decision {id:'Evaluation-for-metastatic-therapy', name:'BINV-20'})
MERGE (Metastatic_site:ClinicalParameter {name:'Metastatic-site'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(Metastatic_site)
MERGE (ER_status:ClinicalParameter {name:'ER-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(ER_status)
MERGE (PR_status:ClinicalParameter {name:'PR-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(PR_status)
MERGE (HER2_status:ClinicalParameter {name:'HER2-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(HER2_status)
MERGE (rule_Evaluation_for_metastatic_therapy_0:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_0'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_0)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site:Condition {param:'Metastatic_site', value:'_bone_'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_ER_status:Condition {param:'ER_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_0_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_PR_status:Condition {param:'PR_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_0_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_HER2_status:Condition {param:'HER2_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_0_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_0__denosumab__OR__zoledronic_acid__OR__pamidronate_:ActionRecommendation {name:'"denosumab" OR "zoledronic acid" OR "pamidronate"'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_0__denosumab__OR__zoledronic_acid__OR__pamidronate_)
MERGE (rule_Evaluation_for_metastatic_therapy_1:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_1'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_1)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_ER_status:Condition {param:'ER_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_PR_status:Condition {param:'PR_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status:Condition {param:'HER2_status', value:'_Low___Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_1__BINV_21_:ActionRecommendation {name:'"BINV-21"'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_1__BINV_21_)
MERGE (rule_Evaluation_for_metastatic_therapy_2:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_2'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_2)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_ER_status:Condition {param:'ER_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_PR_status:Condition {param:'PR_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status:Condition {param:'HER2_status', value:'_Low___Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_2__BINV_21_:ActionRecommendation {name:'"BINV-21"'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_2__BINV_21_)
MERGE (rule_Evaluation_for_metastatic_therapy_3:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_3'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_3)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_ER_status:Condition {param:'ER_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_PR_status:Condition {param:'PR_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status:Condition {param:'HER2_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_3__BINV_23_:ActionRecommendation {name:'"BINV-23"'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_3__BINV_23_)
MERGE (rule_Evaluation_for_metastatic_therapy_4:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_4'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_4)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_ER_status:Condition {param:'ER_status', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_PR_status:Condition {param:'PR_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status:Condition {param:'HER2_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_4__BINV_23_:ActionRecommendation {name:'"BINV-23"'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_4__BINV_23_)
MERGE (rule_Evaluation_for_metastatic_therapy_5:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_5'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_5)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_ER_status:Condition {param:'ER_status', value:'_Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_PR_status:Condition {param:'PR_status', value:'_Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status:Condition {param:'HER2_status', value:'_Positive_'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_5__BINV_25_:ActionRecommendation {name:'"BINV-25"'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_5__BINV_25_)
MERGE (rule_Evaluation_for_metastatic_therapy_6:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_6'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_6)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_Metastatic_site:Condition {param:'Metastatic_site', value:'Unknown'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_ER_status:Condition {param:'ER_status', value:'_Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_PR_status:Condition {param:'PR_status', value:'_Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status:Condition {param:'HER2_status', value:'_Low___Negative_'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_6__BINV_26_:ActionRecommendation {name:'"BINV-26"'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_6__BINV_26_)
MERGE (BINV_25_1:Decision {id:'BINV-25-1', name:'BINV-25-1'})
MERGE (rule_BINV_25_1_0:DecisionRule {id:'rule_BINV_25_1_0'})
MERGE (BINV_25_1)-[:HAS_RULE]->(rule_BINV_25_1_0)
MERGE (outcome_rule_BINV_25_1_0__BINV_Q_3_:ActionRecommendation {name:'"BINV-Q-3"'})
MERGE (rule_BINV_25_1_0)-[:HAS_OUTCOME]->(outcome_rule_BINV_25_1_0__BINV_Q_3_)
MERGE (First_line_therapy_for_HRpHER2n:Decision {id:'First-line-therapy-for-HRpHER2n', name:'BINV-21-1'})
MERGE (Visceral_crisis:ClinicalParameter {name:'Visceral-crisis'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(Visceral_crisis)
MERGE (Prior_endocrine_therapy_within_1y:ClinicalParameter {name:'Prior-endocrine-therapy-within-1y'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(Prior_endocrine_therapy_within_1y)
MERGE (menopause:ClinicalParameter {name:'menopause'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(menopause)
MERGE (rule_First_line_therapy_for_HRpHER2n_0:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_0'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_0)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis:Condition {param:'Visceral_crisis', value:'true'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Prior_endocrine_therapy_within_1y:Condition {param:'Prior_endocrine_therapy_within_1y', value:'Unknown'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_0_Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Prior_endocrine_therapy_within_1y)-[:CONDITION_ON]->(Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_menopause:Condition {param:'menopause', value:'Unknown'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_0_menopause)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_menopause)-[:CONDITION_ON]->(menopause)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_0__BINV_Q_:ActionRecommendation {name:'"BINV-Q"'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_0__BINV_Q_)
MERGE (rule_First_line_therapy_for_HRpHER2n_1:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_1'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_1)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis:Condition {param:'Visceral_crisis', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Prior_endocrine_therapy_within_1y:Condition {param:'Prior_endocrine_therapy_within_1y', value:'Unknown'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_1_Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Prior_endocrine_therapy_within_1y)-[:CONDITION_ON]->(Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_menopause:Condition {param:'menopause', value:'Unknown'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_1_menopause)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_menopause)-[:CONDITION_ON]->(menopause)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_1__BINV_P_:ActionRecommendation {name:'"BINV-P"'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_1__BINV_P_)
MERGE (rule_First_line_therapy_for_HRpHER2n_2:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_2'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_2)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis:Condition {param:'Visceral_crisis', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y:Condition {param:'Prior_endocrine_therapy_within_1y', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y)-[:CONDITION_ON]->(Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_menopause:Condition {param:'menopause', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_menopause)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_menopause)-[:CONDITION_ON]->(menopause)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_2__BINV_P_:ActionRecommendation {name:'"BINV-P"'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_2__BINV_P_)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_2__Tamoxifen__OR__Toremifene_:ActionRecommendation {name:'"Tamoxifen" OR "Toremifene"'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_2__Tamoxifen__OR__Toremifene_)
MERGE (BINV_23_1:Decision {id:'BINV-23-1', name:'BINV-23-1'})
MERGE (rule_BINV_23_1_0:DecisionRule {id:'rule_BINV_23_1_0'})
MERGE (BINV_23_1)-[:HAS_RULE]->(rule_BINV_23_1_0)
MERGE (outcome_rule_BINV_23_1_0__BINV_P__OR__BINV_Q_3_:ActionRecommendation {name:'"BINV-P" OR "BINV-Q-3"'})
MERGE (rule_BINV_23_1_0)-[:HAS_OUTCOME]->(outcome_rule_BINV_23_1_0__BINV_P__OR__BINV_Q_3_)