MERGE (Evaluation_for_metastatic_therapy:Decision {id:'Evaluation-for-metastatic-therapy', name:'BINV-20'})
MERGE (Metastatic_site:ClinicalParameter {name:'Metastatic-site'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(Metastatic_site)
MERGE (ER_status:ClinicalParameter {name:'ER-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(ER_status)
MERGE (PR_status:ClinicalParameter {name:'PR-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(PR_status)
MERGE (HER2_status:ClinicalParameter {name:'HER2-status'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_INPUT]->(HER2_status)
MERGE (rule_Evaluation_for_metastatic_therapy_0:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_0'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_0)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site:Condition {param:'Metastatic_site', value:'on'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_0_Metastatic_site)-[:CONDITION_ON]->(Metastatic_site)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_0_enosumab__OR__zoledronic_acid__OR__pamidronat:ActionRecommendation {name:'"denosumab" OR "zoledronic acid" OR "pamidronate"'})
MERGE (rule_Evaluation_for_metastatic_therapy_0)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_0_enosumab__OR__zoledronic_acid__OR__pamidronat)
MERGE (rule_Evaluation_for_metastatic_therapy_1:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_1'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_1)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_ER_status:Condition {param:'ER_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status:Condition {param:'HER2_status', value:'ow___Negativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_1_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_1_BINV_21:TransitionOutcome {name:'BINV-21'})
MERGE (rule_Evaluation_for_metastatic_therapy_1)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_1_BINV_21)
MERGE (BINV_21:Decision {id:'BINV-21'})
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_1_BINV_21)-[:LEADS_TO_DECISION]->(BINV_21)
MERGE (rule_Evaluation_for_metastatic_therapy_2:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_2'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_2)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_PR_status:Condition {param:'PR_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status:Condition {param:'HER2_status', value:'ow___Negativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_2_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_2_BINV_21:TransitionOutcome {name:'BINV-21'})
MERGE (rule_Evaluation_for_metastatic_therapy_2)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_2_BINV_21)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_2_BINV_21)-[:LEADS_TO_DECISION]->(BINV_21)
MERGE (rule_Evaluation_for_metastatic_therapy_3:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_3'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_3)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_ER_status:Condition {param:'ER_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status:Condition {param:'HER2_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_3_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_3_BINV_23:TransitionOutcome {name:'BINV-23'})
MERGE (rule_Evaluation_for_metastatic_therapy_3)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_3_BINV_23)
MERGE (BINV_23:Decision {id:'BINV-23'})
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_3_BINV_23)-[:LEADS_TO_DECISION]->(BINV_23)
MERGE (rule_Evaluation_for_metastatic_therapy_4:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_4'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_4)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_PR_status:Condition {param:'PR_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status:Condition {param:'HER2_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_4_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_4_BINV_23:TransitionOutcome {name:'BINV-23'})
MERGE (rule_Evaluation_for_metastatic_therapy_4)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_4_BINV_23)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_4_BINV_23)-[:LEADS_TO_DECISION]->(BINV_23)
MERGE (rule_Evaluation_for_metastatic_therapy_5:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_5'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_5)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_ER_status:Condition {param:'ER_status', value:'egativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_PR_status:Condition {param:'PR_status', value:'egativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status:Condition {param:'HER2_status', value:'ositiv'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_5_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_5_BINV_25:TransitionOutcome {name:'BINV-25'})
MERGE (rule_Evaluation_for_metastatic_therapy_5)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_5_BINV_25)
MERGE (BINV_25:Decision {id:'BINV-25'})
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_5_BINV_25)-[:LEADS_TO_DECISION]->(BINV_25)
MERGE (rule_Evaluation_for_metastatic_therapy_6:DecisionRule {id:'rule_Evaluation_for_metastatic_therapy_6'})
MERGE (Evaluation_for_metastatic_therapy)-[:HAS_RULE]->(rule_Evaluation_for_metastatic_therapy_6)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_ER_status:Condition {param:'ER_status', value:'egativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_ER_status)-[:CONDITION_ON]->(ER_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_PR_status:Condition {param:'PR_status', value:'egativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_PR_status)-[:CONDITION_ON]->(PR_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status:Condition {param:'HER2_status', value:'ow___Negativ'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_CONDITION]->(cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status)
MERGE (cond_rule_Evaluation_for_metastatic_therapy_6_HER2_status)-[:CONDITION_ON]->(HER2_status)
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_6_BINV_26:TransitionOutcome {name:'BINV-26'})
MERGE (rule_Evaluation_for_metastatic_therapy_6)-[:HAS_OUTCOME]->(outcome_rule_Evaluation_for_metastatic_therapy_6_BINV_26)
MERGE (BINV_26:Decision {id:'BINV-26'})
MERGE (outcome_rule_Evaluation_for_metastatic_therapy_6_BINV_26)-[:LEADS_TO_DECISION]->(BINV_26)
MERGE (BINV_25_1:Decision {id:'BINV-25-1', name:'BINV-25-1'})
MERGE (rule_BINV_25_1_0:DecisionRule {id:'rule_BINV_25_1_0'})
MERGE (BINV_25_1)-[:HAS_RULE]->(rule_BINV_25_1_0)
MERGE (outcome_rule_BINV_25_1_0_BINV_Q_3:TransitionOutcome {name:'BINV-Q-3'})
MERGE (rule_BINV_25_1_0)-[:HAS_OUTCOME]->(outcome_rule_BINV_25_1_0_BINV_Q_3)
MERGE (BINV_Q_3:Decision {id:'BINV-Q-3'})
MERGE (outcome_rule_BINV_25_1_0_BINV_Q_3)-[:LEADS_TO_DECISION]->(BINV_Q_3)
MERGE (First_line_therapy_for_HRpHER2n:Decision {id:'First-line-therapy-for-HRpHER2n', name:'BINV-21-1'})
MERGE (Visceral_crisis:ClinicalParameter {name:'Visceral-crisis'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(Visceral_crisis)
MERGE (Prior_endocrine_therapy_within_1y:ClinicalParameter {name:'Prior-endocrine-therapy-within-1y'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(Prior_endocrine_therapy_within_1y)
MERGE (menopause:ClinicalParameter {name:'menopause'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_INPUT]->(menopause)
MERGE (rule_First_line_therapy_for_HRpHER2n_0:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_0'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_0)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis:Condition {param:'Visceral_crisis', value:'true'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_0_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_0_BINV_Q:TransitionOutcome {name:'BINV-Q'})
MERGE (rule_First_line_therapy_for_HRpHER2n_0)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_0_BINV_Q)
MERGE (BINV_Q:Decision {id:'BINV-Q'})
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_0_BINV_Q)-[:LEADS_TO_DECISION]->(BINV_Q)
MERGE (rule_First_line_therapy_for_HRpHER2n_1:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_1'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_1)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis:Condition {param:'Visceral_crisis', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_1_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_1_BINV_P:TransitionOutcome {name:'BINV-P'})
MERGE (rule_First_line_therapy_for_HRpHER2n_1)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_1_BINV_P)
MERGE (BINV_P:Decision {id:'BINV-P'})
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_1_BINV_P)-[:LEADS_TO_DECISION]->(BINV_P)
MERGE (rule_First_line_therapy_for_HRpHER2n_2:DecisionRule {id:'rule_First_line_therapy_for_HRpHER2n_2'})
MERGE (First_line_therapy_for_HRpHER2n)-[:HAS_RULE]->(rule_First_line_therapy_for_HRpHER2n_2)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis:Condition {param:'Visceral_crisis', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Visceral_crisis)-[:CONDITION_ON]->(Visceral_crisis)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y:Condition {param:'Prior_endocrine_therapy_within_1y', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_Prior_endocrine_therapy_within_1y)-[:CONDITION_ON]->(Prior_endocrine_therapy_within_1y)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_menopause:Condition {param:'menopause', value:'false'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_CONDITION]->(cond_rule_First_line_therapy_for_HRpHER2n_2_menopause)
MERGE (cond_rule_First_line_therapy_for_HRpHER2n_2_menopause)-[:CONDITION_ON]->(menopause)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_2_BINV_P:TransitionOutcome {name:'BINV-P'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_2_BINV_P)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_2_BINV_P)-[:LEADS_TO_DECISION]->(BINV_P)
MERGE (outcome_rule_First_line_therapy_for_HRpHER2n_2_amoxifen__OR__Toremifen:ActionRecommendation {name:'"Tamoxifen" OR "Toremifene"'})
MERGE (rule_First_line_therapy_for_HRpHER2n_2)-[:HAS_OUTCOME]->(outcome_rule_First_line_therapy_for_HRpHER2n_2_amoxifen__OR__Toremifen)
MERGE (BINV_23_1:Decision {id:'BINV-23-1', name:'BINV-23-1'})
MERGE (rule_BINV_23_1_0:DecisionRule {id:'rule_BINV_23_1_0'})
MERGE (BINV_23_1)-[:HAS_RULE]->(rule_BINV_23_1_0)
MERGE (outcome_rule_BINV_23_1_0_BINV_P__OR__BINV_Q_3:TransitionOutcome {name:'BINV-P" OR "BINV-Q-3'})
MERGE (rule_BINV_23_1_0)-[:HAS_OUTCOME]->(outcome_rule_BINV_23_1_0_BINV_P__OR__BINV_Q_3)
MERGE (BINV_P__OR__BINV_Q_3:Decision {id:'BINV-P" OR "BINV-Q-3'})
MERGE (outcome_rule_BINV_23_1_0_BINV_P__OR__BINV_Q_3)-[:LEADS_TO_DECISION]->(BINV_P__OR__BINV_Q_3)