host:
  hostname: "localhost"
  port: 50060

group_chat_manager:
  topic_type: "group_chat"
  max_rounds: 3

writer_agent:
  topic_type: "Writer"
  description: "Writer for creating any text content."
  system_message: "You are a one sentence Writer and provide one sentence content each time"

editor_agent:
  topic_type: "Editor"
  description: "Editor for planning and reviewing the content."
  system_message: "You are an Editor. You provide just max 15 words as feedback on writers content."

ui_agent:
  topic_type: "ui_events"
  artificial_stream_delay_seconds:
    min: 0.05
    max: 0.1

client_config:
# Use Open AI with key
  model: qwen2.5-coder:32b-instruct-q5_0
  api_key: sk-...
  base_url: http://10.0.40.49:11434/v1
  temperature: 0.1
  max_tokens: 4096
  top_p: 0.95
  top_k: 40
  run_stream: true
  model_info:
    vision: false
    function_calling: true
    json_output: true
    family: Unknown
    structured_output: true